### ISSUE TITLE
Inkscape generated svg

### ISSUE THREAD

**Issue by Alexander3** [andrewplummer/Positionable#1]
My page contains embeded svg created in Inkscape. It gives following error after using extension : 
`positionable.js:1659 Uncaught TypeError: Cannot read property 'background' of undefined`
in line `} else if (el.style.background.match(/positionable-extension/)) {`
After quick debuging it seems `sodipodi:namedview` tag was problem.

Win 10, Chrome 51.0.2704.84 m (64-bit)

Tag that was responsible for error in listing below.

```
<svg xmlns:dc="http://purl.org/dc/elements/1.1/" xmlns:cc="http://creativecommons.org/ns#" xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" xmlns:sodipodi="http://sodipodi.sourceforge.net/DTD/sodipodi-0.dtd" xmlns:inkscape="http://www.inkscape.org/namespaces/inkscape" xml:space="preserve" width="1525" height="597.5" version="1.1" style="clip-rule:evenodd;fill-rule:evenodd;image-rendering:optimizeQuality;shape-rendering:geometricPrecision;text-rendering:geometricPrecision" viewBox="0 0 28422.717 11136.578" id="svg2" version="0.91 r13725" docname="Piętra full2.1.svg" class="svg-embed positionable-extension-positioned-element">

    //This tag has no el.style.background
    <sodipodi:namedview pagecolor="#ffffff" bordercolor="#666666" borderopacity="1" objecttolerance="10" gridtolerance="10" guidetolerance="10" pageopacity="0" pageshadow="2" window-width="1920" window-height="1017" id="namedview100" showgrid="false" zoom="2.2156644" cx="1187.7229" cy="335.6779" window-x="-8" window-y="-8" window-maximized="1" current-layer="flats" units="px" fit-margin-top="0" fit-margin-left="0" fit-margin-right="0" fit-margin-bottom="0"></sodipodi:namedview>
    <g groupmode="layer" id="layer1" label="Layer 1" transform="translate(0,635.57835)">

    </g>

...
```

**Comment by andrewplummer** [comment]
Hi, sorry for the delay on this.

I tried to repro this locally but couldn't (my <sodipodi> element had a `style` object). However the fix is fairly clear (check for the `style` object), so I published an updated version, so try it out!

With this fix, it should no longer error when SVG elements are present, but are you actually trying to use it ON SVG elements? If so you might run into some errors.

After diving into your issue a bit, it occured to me that SVG won't really work here as the attributes needed to be updated are different. I started working on support for this, but it begs the question: what kind of output would be expected here?

Normally the output would be CSS, however, with SVG the styles are essentially embedded. Would the entire SVG object be expected? Anyway will have to have a thought about this before support can be added I suppose.

At any rate the error should be fixed now!
