### ISSUE TITLE
Relative position elements support

### ISSUE THREAD

**Issue by abulgatz** [andrewplummer/Positionable#3]
Awesome extension!

Any chance of making this work on relatively positioned elements?

**Comment by abulgatz** [comment]
Needs one line changed to work with relatively positioned elements.

Change line 1679 from:
`return style.position === 'absolute' || style.position === 'fixed';`

To:
`return style.position === 'absolute' || style.position === 'fixed' || style.position === 'relative';`

**Comment by andrewplummer** [comment]
Is there much of a need for working on relatively positioned elements? If you're setting absolute pixel values, why not use "absolute" instead?

Even if there is a good use case, relative elements can still be targeted using the "Include elements matching" option, which will override. The `absolute || fixed` is just a default. I think this is a better default to have as well because there are a lot of other reasons for making an element "position: relative" than wanting to move it around (creating a stacking context is the most common one).

**Comment by andrewplummer** [comment]
Ok... the new version is released... it supports relative elements by targeting them with a selector, same way as before, but this time it will force them to relative if they're static, so you don't have to do it yourself!
